export const services = [
  {
    id: 1,
    title: "Internal Medicine",
    duration: "1 hr",
    priceArabic: "80 دولار أمريكي",
    priceEnglish: "80 US$",
    code: "internal-medicine",
  },
  {
    id: 2,
    title: "Women's Health",
    duration: "2 hr",
    priceArabic: "140 دولار أمريكي",
    priceEnglish: "140 US$",
    code: "womens-health",
  },
  {
    id: 3,
    title: "Travel Clinic",
    duration: "1 hr",
    priceArabic: "120 دولار أمريكي",
    priceEnglish: "120 US$",
    code: "travel-clinic",
  },
  {
    id: 4,
    title: "Emergency Services",
    duration: "2 hr",
    priceArabic: "120 دولار أمريكي",
    priceEnglish: "120 US$",
    code: "emergency-services",
  },
  {
    id: 5,
    title: "Radiology Services",
    duration: "2 hr",
    priceArabic: "140 دولار أمريكي",
    priceEnglish: "140 US$",
    code: "radiology-services",
  },
  {
    id: 6,
    title: "Wound Care",
    duration: "1 hr",
    priceArabic: "90 دولار أمريكي",
    priceEnglish: "90 US$",
    code: "wound-care",
  },
  {
    id: 7,
    title: "Pharmacy",
    duration: "2 hr",
    priceArabic: "120 دولار أمريكي",
    priceEnglish: "120 US$",
    code: "pharmacy",
  },
  {
    id: 8,
    title: "Dermatology",
    duration: "1 hr",
    priceArabic: "120 دولار أمريكي",
    priceEnglish: "120 US$",
    code: "dermatology",
  },
  {
    id: 9,
    title: "Cooking Classes",
    duration: "2 hr",
    priceArabic: "",
    priceEnglish: "",
    code: "cooking-classes",
  },
];
